[tools]
k3d = "latest"
k9s = "latest"
kubectl = "latest"
pre-commit = "latest"
python = "3.13"
ruff = "latest"
trivy = "latest"
uv = "latest"

[settings]
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = ["python"]
experimental = true

[env]
APP_REPO = 'dev-project'
GITOPS_REPO = 'study-app-gitops'

[hooks]
enter = "bash ./scripts/setup_project"


[tasks.k8s-setup-local]
description = "Set up a basic Kubernetes cluster for development."
run = "bash ./kubernetes/setup_cluster_local"

[tasks.k8s-setup-minimal]
description = "Set up a minimal cluster for testing and does not apply nothing."
run = "bash ./kubernetes/setup_cluster_minimal"

[tasks.e2e-test]
description = "Run end-to-end test on the Kubernetes deploymnet"
run = "cd ./kubernetes && uv run e2e_test.py"
