apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# List of all resources to be included in this kustomization.
# These can be individual YAML files or directories containing multiple manifests.
# The order matters if there are dependencies between resources.
resources:
  - namespace.yaml
  - backend
  - frontend

# All generated resources are assigned to the study-app namespace unless they specify one explicitly.
namespace: study-app

# Useful for environment-based deployments (e.g., dev/staging/prod). This adds dev- to the names of resources.
namePrefix: dev-

# Patch: updates images by name across all resources. image: backend:latest Kustomize will turn it into image: backend:dev
# This is helpful for deploying different versions of images in different environments.
# Here, we are setting the backend and frontend images to use the 'dev' tag.
# For example, if the original image is backend:latest, it will be changed to backend:dev.
# This allows for easy switching between different versions of images without modifying the original manifests.
images:
  - name: backend
    newTag: dev
  - name: frontend
    newTag: dev
